module.exports = {
  ORDER: {
    ASC: "asc",
    DESC: "desc",
  },
  SORT: {
    CREATED_AT: "createdAt",
    UPDATED_AT: "createdAt",
    TITLE: "title",
    CATEGORY: "category",
  },
  STATUS_CODE: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    CONFLICT: 409,
  },

  ERROR_TYPE: {
    API_ERROR: "API ERROR",
    VALIDATION_ERROR: "Validation Error",
    AUTHENTICATION_ERROR: "Authentication Error",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
  },

  ERROR_MESSAGE: {
    DEFAULT: "error",
    USER_NOT_FOUND: "User not found",
    USER_ALREADY_EXIST: "User already exists",
    INVALID_PASSWORD: "Invalid password",
    OTP_EXPIRED: "OTP has been expired",
    OTP_CREATION_ERROR: "Failed to Generate OTP",
    OTP_VERIFICATION_FAILED: "OTP verification failed",
    PASSWORD_RESET_EMAIL_ERROR: "Failed to Send Password Reset Email",
    OTP_EMAIL_ERROR: "Failed to Send OTP Email",
    INVALID_OLD_PASSWORD: "Invalid Old Password",
    REFRESH_TOKEN_EXPIRED: "Refresh token has been expired",
    INVALID_REFRESH_TOKEN: "Invalid refresh token",
    TOKEN_NOT_FOUND: "Token not found",
    ACCESS_TOKEN_EXPIRED: "Access token has been expired",
    COMMENT_NOT_FOUND: "Comment not found",
    REPLIES_NOT_FOUND: "Comment replies not found",
    POST_NOT_FOUND: "Post not found",
    PASSWORD_VERIFICATION_ERROR: "Failed to verify password",
    GENERATE_PASSWORD_ERROR: "Failed to Generate Encrypted Password",
    TOKEN_VERIFICATION_ERROR: "Failed to verify token",
    ACCESS_TOKEN_SIGN_ERROR: "Failed to Sign Access Token",
    REFRESH_TOKEN_SIGN_ERROR: "Failed to Sign Refresh Token",
    PASSWORD_RESET_TOKEN_SIGN_ERROR: "Failed to Sign Password Reset Token",
    
  },

  SUCCESS_MESSAGE: {
    DEFAULT: "Success",

    USER_SIGN_UP: "User signed up successfully",
    OPT_SENT: "OTP Code sent successfully",
    USER_LOG_IN: "User logged in successfully",
    PASSWORD_RESET_EMAIL_SENT: "Password reset email sent successfully",
    PASSWORD_RESET: "Password reset successfully",
    PASSWORD_CHANGE: "Password changed successfully",
    TOKEN_REFRESH: "Token Refreshed Successfully",
    USER_LOG_OUT: "User logged out successfully",

    COMMENT_CREATED: "Comment created successfully",
    COMMENTS_FETCHED: "Comments fetched successfully",
    COMMENT_DELETED: "Comment deleted successfully",
    COMMENT_UPDATED: "Comment updated successfully",
    REPLIES_FETCHED: "Replies of comment fetched successfully",

    USER_FETCH: "User fetched successfully",
    USER_UPDATED: "User updated successfully",

    POSTS_FETCH: "Posts fetched successfully",
    USER_POSTS_FETCH: "User posts fetched successfully",
    POST_FETCH: "A post fetched successfully",
    POST_CREATED: "Post created successfully",
    POST_UPDATED: "Post updated successfully",
    POST_DELETED: "Post deleted successfully",
    POST_CATEGORIES_FETCH: "Post Categories fetched successfully",
  },
};
